source "https://rubygems.org"
ruby "3.2.2"
gem "rails", "~> 8.1.1"
gem "puma"
gem "bootsnap", require: false
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "sqlite3", "~> 1.4"
gem "sqlite3", "~> 1.4"
gem "sqlite3", "~> 1.4"
